name = "lahva"
version = "0.2.0"
license = "MIT-license"
maintainer = ["@psteinbach"]
author = ["Pit Steinbach"]
description = "Linear Algebra on Heterogenous/Vectorized Architecture"
keywords = ["LAHVA", "gpu", "linear algebra"]
copyright = "Copyright 2025 P. Steinbach"

[build]
link = ["lapack", "blas"]

[library]
source-dir = "src/cpu"
